.ss 12 0
.hw gro-blad
.
.TH groblad 1 "JUL 2013" Groblad "User Manuals"
.
.
.SH "NAME"
groblad \- record botanical observations
.
.SH "SYNOPSIS"
.B groblad
.RB [ \-f
.IR template ]
.I file
.
.SH "DESCRIPTION"
.B groblad
makes it convenient to record 
botanical observations into a text file
for future reference.
.P
Observations are grouped as a list of the species seen at a specific place and time.
The format and fields are based on
the paper field lists used during the census which ended up as
.IR "V\(:asterg\(:otlands Flora" .
See
.BR groblad (5).
.PP
The basic idea is to fill in a template (using a text editor of your choice, which
.IR groblad
starts for you).
When you exit the editor, the observations are trimmed, syntax-checked,
and appended to
.IR file .
.
.SH "OPTIONS"
.IP \-f\ \fItemplate
Use
.I template
instead of
.I ~/.flora
or
.IR INSTALLBASE/lib/groblad/default .
.
.SH "FILES"
.TP
.I ~/.flora
Personal excursion template file. May contain only a subset of
all species. Fields, e.g.
.IR observers ,
may be pre-filled.
.TP
.I INSTALLBASE/lib/gavia/default
Global excursion template file, used if the personal template isn't
available
and none has been given using the
.B \-f
flag.
.TP
.I INSTALLBASE/lib/groblad/species
The list of supported taxa and their taxonomic ordering.
Used by
.B groblad
only to issue warnings about misspelled species names;
you may in fact use any name you choose.
.
.SH "ENVIRONMENT"
.IP GAVIAEDITOR
Specifies the editor to use.
If not set,
.I VISUAL
or
.I EDITOR
is used instead.
If none of these are set, the default is
.BR emacs (1).
.
.SH "AUTHOR"
J\(:orgen Grahn \fI\[fo]grahn+src@snipabacken.se\[fc]
.
.SH "SEE ALSO"
.BR groblad (5),
.BR groblad_report (1).
