.ss 12 0
.de BP
.IP \\fB\\$*
..
.hw gro-blad
.
.TH groblad_report 1 "AUG 2013" Groblad "User Manuals"
.
.
.SH "NAME"
groblad_report \- pretty-print botanical observations
.
.SH "SYNOPSIS"
.B groblad_report
.RB [ --ms ]
.RI [ file ]
\&...
.br
.B groblad_report
.B --sundh
.RI [ file ]
\&...
.br
.B groblad_report
.RB --svalan
.RB [ \-s ]
.RB [ --me
.IR name ]
\&...
.RI [ file ]
\&...
.
.SH "DESCRIPTION"
.B groblad_report
rearranges one or more files (see
.BR groblad (5))
into a list of species in systematic order
and formats it as
.B troff
source to standard output.
.P
This is useful for reporting findings to organizations which
collect such data,
or perhaps for including in an article or report.
.P
Some syntax checking is also performed.
Among other things, species which are unknown are skipped,
and result in warnings.
.
.SH "OPTIONS"
.
.BP --ms
Generate troff \-ms source for a nicely formatted list of observations
by species, and in systematic order.
This is the default.
.
.BP --sundh
Generate troff source with
.BR tbl (1)
tables, one line per finding.
Since
.B tbl
input is TAB-separated data, this happens to be compatible with
certain Microsoft Excel-fixated computer systems.
Use for example as:
.IP
groblad_report --sundh file | groff -ms -t > file.ps
.
.BP --svalan
Like
.BR --sundh ,
but with slightly different and quite a lot more useless columns,
and no taxonomical ordering.
This matches the text file (\[lq]Excel\[rq]) import format currently used by
.IR Artportalen ;
.IR "Rapportsystemet f\(:or v\(:axter" ,
.IR \[fo]http://www.artportalen.se/plants/\[fc] .
.
.BP \-s
Exclude species not known to groblad, instead of bringing them in and hoping they
are accepted by
.I Artportalen
anyway.
Only useful with
.BR --svalan ;
the other output options use taxonomical ordering and/or want to print the latin name.
.IP
This used to be the default.
.
.BP --me\ \fIname
Only useful with
.BR --svalan .
Give a name of the reporter (i.e. yourself), to distinguish him from co-observers.
May be given multiple times, if different names or spellings are given in the input.
.
.
.SH "FILES"
.TP
.I INSTALLBASE/lib/groblad/species
The list of accepted taxa
and their scientific names (which are included in the output).
.
.SH "AUTHOR"
J\(:orgen Grahn \fI\[fo]grahn+src@snipabacken.se\[fc]
.
.SH "SEE ALSO"
.BR groblad (5),
.BR groblad_cat (1),
.BR groblad_grep (1),
.BR groblad (1),
.BR groblad_fv (1),
.BR troff (1),
.BR tbl (1).
