.\" $Id: groblad_report.1,v 1.3 2007-09-27 22:28:02 grahn Exp $
.\" 
.\"
.TH groblad_report 1 "SEP 2007" Groblad "User Manuals"
.
.
.SH "NAME"
groblad_report \- pretty-print botanical observations
.
.SH "SYNOPSIS"
.B groblad_report
.RB [ --ms
|
.B --svalan
|
.BR --sundh ]
.RI [ file ...]
.
.SH "DESCRIPTION"
.B groblad_report
rearranges one or more files (see
.BR groblad (5))
into a list of species in systematic order
and formats it as
.B troff
source to standard output.
.P
This is useful for reporting findings to organizations which
collect such data,
or perhaps for including in an article or report.
.P
Some basic syntax checking is performed.
Among other things, species which are unknown are skipped,
and result in warnings.
.
.SH "OPTIONS"
.
.IP --ms
Generate troff \-ms source for a nicely formatted list of observations
by species, and in systematic order.
This is the default.
.
.IP --sundh
Generate troff source with
.BR tbl (1)
tables, one line per finding.
Since
.B tbl
input is TAB-separated data, this happens to be compatible with
certain Microsoft Excel-fixated computer systems.
Use for example as:
.IP
groblad_report --sundh file | groff -ms -t > file.ps
.
.IP --svalan
Like
.BR --sundh ,
but with slightly different and quite a lot more useless columns.
.B "Not implemented" .
.
.SH "FILES"
.TP
.I INSTALLBASE/lib/groblad/species
The list of accepted species, subspecies, hybrids and forms,
and their scientific names (which are included in the output).
.
.SH "AUTHOR"
J\(:orgen Grahn \fI<jgrahn@algonet.se>
.
.SH "SEE ALSO"
.BR groblad (1),
.BR groblad (5),
.BR troff (1),
.BR tbl (1).
