.\" $Id: groblad_fv.1,v 1.6 2011-07-16 15:04:00 grahn Exp $
.
.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.ds + [+]
.
.TH groblad_fv 1 "JUL 2011" Groblad "User Manuals"
.
.
.SH "NAME"
groblad_fv \- report botanical observations to Artportalen
.
.
.SH "SYNOPSIS"
.
.B groblad_fv
.I file
\&...
.br
.B groblad_fv
.B --help
.br
.B groblad_fv
.B --version
.
.
.SH "DESCRIPTION"
.
.B groblad_fv
is similar to
.BR groblad_report (1),
but uses another input format and is better suited for few, detailed reports to
.I Artportalen
rather than mass-imports of many observations.
The latter are unsuitable for reports in the scope of
.BR Florav\(:akteriet ,
since these cannot currently (2010\-2011) be edited once they have been submitted.
.
.PP
It's perhaps simplest understood as a simple transformation between a human-readable
and editable text file format and the tab-separated format accepted by the so-called
\[lq]Excel import\[rq] feature of Artportalen.
.
However, it also simplifies some tedious aspects like calculation of coordinate accuracy
and end date, and performs some syntax checks.
.PP
The converted data is printed to standard output. You then copy & paste it into Artportalen,
as documented (\[lq]Excel import\[rq]).
.
.
.SS "Input file format"
.
The input is a text file, with records being a series
.B "field name : value"
lines. Records are separated by blank lines.
Lines which start with
.B #
are comments and are thus ignored.
You may break lines for readability, but then you have to indent the following lines with at least
one space or TAB.
.
.PP
Fields generally map 1:1 to the \[lq]Excel import\[rq] columns, but you don't have to list every one
of them, they don't have to appear in any specific order, and some have sane defaults.
.PP
The fields are as follows. The numbered ones are \[lq]Excel import\[rq] columns; others are
my invention and translate to columns.
The descriptions are my interpretation of the documentation in the official Excel template and/or the
user guide. I provide them here for convenience only, and it's not complete documentation.
.PP
Things which are extensions in
.BR groblad_fv (1)
are marked \*+.
.
.BP  1.\~Artnamn
A name for the taxon, or
.B saknas
if it is not known by Artportalen.
.
.BP  2.\~Antal
.BP  3.\~Enhet
.B Antal
and
.B Enhet
belong together.
The latter is one of
.BR "buskar" ,
.BR "m2" ,
.BR "plantor" ,
.BR "träd" ,
.BR "skott" ,
.BR "strån" ,
.BR "tuvor" ,
.BR "stjälkar" ,
.BR "bladskivor" ,
.BR "stänglar" ,
.BR "dm2" ,
.BR "cm2" ,
.BR "kapslar" ,
.BR "kolonier" ,
.BR "bålar" ,
.BR "mycel" ,
.BR "fruktkroppar" .
.BP
\*+ You can also use names in singularis, and proper typography like
.BR m² ,
.BR dm² ,
.BR cm² .
.BP
\*+ You can skip the separate
.B Enhet
field and just say e.g.
.IR "Antal: 1 stängel" .
.
.BP  4.\~Antal\~substrat
Mostly for epiphytes, I suppose.
.
.BP  5.\~Stadium
One of
.BR "Vilstadium" ,
.BR "Knoppbristning" ,
.BR "Fullt utvecklade blad" ,
.BR "Blomknopp" ,
.BR "Blomning" ,
.BR "Överblommad" ,
.BR "I frukt" ,
.BR "Frukt-/fröspridning" ,
.BR "Gulnande löv/blad" ,
.BR "Bladfällning, vissnar" ,
.BR "Vinterståndare" .
There are plenty of others, but those are not applicable to fanerogams.
.
.BP  6.\~Lokalnamn
Place name. Vaguely described as
.IR "\[lq]helst ett geografiskt namn och därefter avstånd och riktning vid behov\[rq]" .
.
.BP  7.\~Nordkoordinat/latitud
Synonym
.BR Nordkoordinat .
.
.BP  8.\~Ostkoordinat/longitud
Synonym
.BR Ostkoordinat .
.
.BP  9.\~Noggrannhet
These three together form the coordinate.
.B Noggrannhet
is one of
.BR "5\ m" ,
.BR "10\ m" ,
.BR "25\ m" ,
.BR "50\ m" ,
.BR "100\ m" ,
.BR "250\ m" ,
.BR "500\ m" ,
.BR "1000\ m" ,
.BR "2500\ m" ,
.BR "5000\ m" .
That's right; you can't specify 1m resolution.
.
.BP \*+\ Koordinat
A simpler way to specify a RT90 coordinate in the traditional format, where the
number of digits implicitly specifies the accuracy. For example,
.I "Koordinat:\ 644501\ 136330"
is the same thing as specifying
.IR 6445010 ,
.IR 1363300 ,
.IR 10\ m .
.
.BP 10.\~Startdatum
.
.BP 11.\~Slutdatum
These two are on the form
.BR "2007\-04\-17" .
\*+ If you omit
.B Slutdatum
it is copied from
.BR Startdatum .
.
.BP 12.\~Kommentar
Information which cannot be given in other fields.
.
.BP 13.\~Det/conf
Who determined or confirmed which taxon it was, and when.
.
.BP 14.\~Samling
The user guide and the Excel sheet give conflicting documentation for this one.
Both agree that you can say
.B "Eget"
(you have a specimen in your private herbarium) or
.BR "Annat" .
The Excel sheet also lists
.BR "NRM, Sthlm" ;
.BR "Göteborg" ;
.BR "Lund" ;
.BR "Uppsala" ;
.BR "Uppsala, SLU" ;
.BR "Umeå" .
.
.BP 15.\~Accessionsnr
Relates to the ID given to the collect in
.BR Samling .
.
.PP
The following three come in two versions:
pick a predefined name, or write your own description.
You can also specify both if you're feeling ambitious.
\*+ If you call the field
.BR Substrat ,
.B Biotop
or
.B Trädslag
instead, the predefined version is chosen if you happen to have used the predefined text
verbatim; otherwise it counts as your own description.
.
.BP 16.\~Substrat\~\-\~lista
.BP 17.\~Substrat\~\-\~text
.BP \*+\~Substrat
The predefined names are
.BR "Marken" ,
.BR "Brandplats" ,
.BR "Sand" ,
.BR "Lera" ,
.BR "Kalkrik jord" ,
.BR "Näringsrik jord" ,
.BR "Näringsfattig jord" ,
.BR "Annan mark" ,
.BR "Ved" ,
.BR "Levande träd" ,
.BR "Högstubbe/dött träd" ,
.BR "Låga" ,
.BR "Stubbe" ,
.BR "Övrig död ved" ,
.BR "Annan ved" ,
.BR "Andra växter" ,
.BR "Levande kärlväxter" ,
.BR "Kottar/nötter/ollon" ,
.BR "Lövförna" ,
.BR "Barrförna" ,
.BR "Övriga växtrester" ,
.BR "Andra växter" ,
.BR "Spillning" ,
.BR "Älgspillning" ,
.BR "Rådjursspillning" ,
.BR "Hare/kaninspillning" ,
.BR "Hästspillning" ,
.BR "Kospillning" ,
.BR "Fårspillning" ,
.BR "Annan djurspillning" .
Many of these are of course not applicable for fanerogams.
.
.BP 18.\~Biotop\~\-\~lista
.BP 19.\~Biotop\~\-\~text
.BP \*+\~Biotop
The predefined names are
.BR "Skogsmark" ,
.BR "Ädellövskog" ,
.BR "Triviallövskog" ,
.BR "Blandskog" ,
.BR "Tallskog" ,
.BR "Granskog" ,
.BR "Hässle" ,
.BR "Hygge" ,
.BR "Annan skogsmark" ,
.BR "Ängs- och betesmark" ,
.BR "Öppen buskmark" ,
.BR "Buskbärande mark" ,
.BR "Trädbärande mark" ,
.BR "Annan ängs-/betesmark" ,
.BR "Våtmark" ,
.BR "Rikkärr" ,
.BR "Fattigkärr" ,
.BR "Mosse" ,
.BR "Strand" ,
.BR "Annan våtmark" ,
.BR "Kalfjäll" ,
.BR "Rik fjällhed" ,
.BR "Fattig fjällhed" ,
.BR "Videsnår" ,
.BR "Människoskapad" ,
.BR "Åker" ,
.BR "Allé" ,
.BR "Park/kyrkogård/gräsmatta" ,
.BR "Gårdsmiljö" ,
.BR "Ruderatmark" ,
.BR "Annan människoskapad" .
.
.BP 20.\~Trädslag\~\-\~lista
.BP 21.\~Trädslag\~\-\~text
.BP \*+\~Trädslag
The predefined names are
.BR "Barrträd" ,
.BR "En" ,
.BR "Gran" ,
.BR "Lärk" ,
.BR "Tall" ,
.BR "Annat barrträd" ,
.BR "Ädellövträd" ,
.BR "Alm" ,
.BR "Ask" ,
.BR "Avenbok" ,
.BR "Bok" ,
.BR "Ek" ,
.BR "Fågelbär" ,
.BR "Hassel" ,
.BR "Hästkastanj" ,
.BR "Lind" ,
.BR "Lönn" ,
.BR "Annat ädellövträd" ,
.BR "Triviallövträd" ,
.BR "Apel" ,
.BR "Asp" ,
.BR "Björk" ,
.BR "Gråal/klibbal" ,
.BR "Oxel" ,
.BR "Rönn" ,
.BR "Salix" ,
.BR "Annat trivialt lövträd" .
Unclear what this field really means; it's probably a substrate thing for epiphytes, but the user guide
mentions it as if it's the species of trees growing at the place.
It's uncommon for a place to have only one species of tree though ...
.
.PP
The few following fields are checkboxes in the normal Artportalen input interface.
Here you say
.B X
(\*+ or any other non-empty text)
to check the box.
.
.BP 22.\~Ej\~återfunnen
Not found, even though this is a known locality.
.
.BP 23.\~Andrahandsuppgift
.
.BP 24.\~Osäker\~bestämning
.
.BP 25.\~Utplanterad\~eller\~införd
A bit unclear what this really means. The Excel sheet says
.IR "\[lq]Införd/ospontan. T. ex. importerad med livsmedel eller virke.\[rq]" .
.
.BP 26.\~Intressant\~notering
.
.BP 27.\~Dölj
Unclear exactly what this means. The user guide mentions that sensitive species are automatically
semi-hidden.
.
.BP 28.\~Skydda\~lokalangivelse
Unclear exactly what this means.
.
.BP 29.\~Rapportera\~till\~Rrk
Not applicable.
.
.BP 30.\~Ej\~funnen
Not found, and not known from this locality. Compare with
.B "Ej\~återfunnen"
above.
.
.BP 31.\~Undersökt\~i\~mikroskop
.
.BP 32.\~Syfte
I can't be bothered to understand what this means.
Doesn't seem to be applicable to
.BR Florav\(:akteriet .
.
.BP 33.\~Floraväktarlokal
If you're reporting as part of 
.B Florav\(:akteriet
for an already existing locality, you must give its ID here, e.g.
.IR OV-Fal-1329 .
\*+ In this case the
.B Lokalnamn
field and fields related to coordinates are ignored (and not checked for concistency).
.
.BP 34\-43.\~Medobs
Observers, apart from yourself. You can specify up to ten observers
this way (by repeating this field).
\*+ Synonym
.BR Medobservatör .
.
.BP \*+\~Obsid
The numerical ID of this observation in Artportalen.
Unlike the others, you fill this in
.I after
you have reported.
It serves as proof that you have reported this, and you get a warning when you
run such an observation through
.B groblad_fv
a second time.
Unfortunately, finding out what ID your observation gets is tedious.
You may say something bland like
.B yes
or
.B reported
here, meaning \[lq]yes, I have entered this one but I can't be bothered to find
out which ID it got\[rq].
.
.
.SH "EXAMPLE"
.nf
\fBArtnamn:\fP brudborste
\fBLokalnamn:\fP vägskäl N om Lindö
\fBKoordinat:\fP 643832 136518
\fBStartdatum:\fP 2011-06-23
\fBBiotop:\fP Blandskog
\fBKommentar:\fP ett litet sterilt bestånd

\fBArtnamn:\fP tistelsnyltrot
\fBAntal:\fP 235 stänglar
\fBFloraväktarlokal:\fP OV-Fal-1633
# these four are ignored and only included for reference:
\fBLokalnamn:\fP MÖSSEBERGSPARKEN, Friggeråker f:g
\fBNordkoordinat:\fP 6453355
\fBOstkoordinat:\fP 1367055
\fBNoggrannhet:\fP 100 m
\fBStartdatum:\fP 2011-07-12
\fBKommentar:\fP Inventerades. Separat kartskiss. V om sanatoriet 159,
    i övrigt 76. Men se även OV-Fal-1646.
    I allmänhet storväxta där de fanns.
.fi
.
.
.
.SH "OPTIONS"
.
None.
.
.
.SH "AUTHOR"
J\(:orgen Grahn \fI\[fo]grahn+src@snipabacken.se\[fc]
.
.SH "SEE ALSO"
.BR groblad_report (1).
.PP
.RB \[fo] http://www.artportalen.se/plants/plants_mall_ver81114.xls \[fc]
\- the official annotated Excel template, current in July, 2011.
.PP
.RB \[fo] http://www.artportalen.se/plants/anvandarhandledning.pdf \[fc]
\- the official user guide,
.IR "Anv\(:andarhandledning f\(:or rapportsystemet f\(:or v\(:axter och svampar" .
Artdatabanken SLU 2008.
