.\" $Id: groblad.5,v 1.5 2010-08-29 08:08:15 grahn Exp $
.\" 
.\"
.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.TH groblad 5 "JUL 2013" Groblad "User Manuals"
.
.
.
.SH "NAME"
groblad \- botanical observation file format
.
.SH "DESCRIPTION"
This manual page describes the file format used by the
.I groblad
set of tools for maintaining botanical observations.
The format is based on (but distinct from!)
the paper field lists used during the census which ended up as
.IR "V\(:asterg\(:otlands Flora" ,
and on the text file format of the
.I gavia
bird observation utilities.
.
.PP
The
.BR groblad_fv (1)
utility uses a different format, much more detailed
but less useful for reporting many species from one locality
(i.e. it doesn't map to the abovementioned field lists).
.
.SH "BASIC SYNTAX"
All files use the ISO 8859-1 character set.
Blank lines and comment lines, introduced by a
.IR # ,
are ignored.
.P
A field may be broken into several lines, as long as all lines but the
first are indented with whitespace.
The break and indent counts as one space character.
Thus, these two fields are identical:
.IP
.ft CW
.nf
Comment: East of the Equator, but left of center.
Comment: East of
         the Equator, but
         left of center.
.fi
.
.
.SH "LOCALITIES"
A
.I groblad
file consists of a series of field lists, each for a specific
locality and date
(although nothing prevents you from revisiting a place and adding
to an older list).
Each looks like
.IP
.ft CW
.nf
{
header fields
}{
taxa
}
.fi
.SH "Header fields"
.
.BP place
The place or locality concerned.
.
.BP coordinate
The coordinate of the place in
.IR "\s-1RT90\s0\ 2.5\ gon\ V" ,
aka the
.I "Rikets N\(:at"
or
.IR "Swedish Grid",
with as many significant digits as you feel suitable.
For example,
.I "6436786\ 1385918"
is a point with 1m resolution on the parking lot of Utv\(:angstorp
parish church.  With 10 m resolution that is
.IR "643679\ 138592" ;
with 100m resolution
.IR "64368\ 13859" .
.
.BP
Different coordinate systems like
.I "\s-1SWEREF\ 99\ TM\s0"
may be supported in the future.
.
.BP date
The date, preferably in ISO format, as
.IR yyyy-mm-dd .
.
.BP observers
The person or persons responsible for this field list.
.
.BP comments
Anything else worth noting which does not concern a specific sighting.
.
.BP status
Metadata, e.g. if this excursion has been reported
or published.
.
.PP
Other header fields may be added, but might cause tools to issue a warning.
.
.
.SH "Taxa"
Taxa fields have the format
.IP
.ft CW
<taxon name>: <mark>: <comment>
.LP
The species name should be one of those defined by the file
.I INSTALLBASE/lib/groblad/species
or
.IR INSTALLBASE/lib/groblad/synonyms .
.P
A listed species must have a non-blank mark (by convention, a single
.B #
is used)
or have a nonempty comment field.
Otherwise, it's regarded as
.I not
included in the listing.
.
.
.SH "EXAMPLE"
.IP
.ft CW
.nf
{
place        : åkerkant O om Stora Bäckabo
coordinate   : 64547 13695
date         : 2004-08-22
observers    : JöG
comments     : 
}{
vattenpilört :#: blommande i åkern (inte så vanligt på Falbygden
                 om jag minns rätt)
sminkrot     :#: åtminstone några stora exemplar, som vid Agnestad
}
.fi
.
.SH "FILES"
.TP
.I INSTALLBASE/lib/groblad/species
The list of accepted species, subspecies, hybrids and so on.
This list is based on Dyntaxa,
.IR \[fo]http://www.dyntaxa.se\[fc] .
.
.TP
.I INSTALLBASE/lib/groblad/synonyms
A list of synonyms to the accepted names, for cases when the author
prefers an alternate spelling or a dialectal name.
.
.SH "AUTHOR"
J\(:orgen Grahn \fI\[fo]grahn+src@snipabacken.se\[fc]
.
.
.SH "SEE ALSO"
.BR groblad (1),
.BR groblad_fv (1),
.BR gavia (5).
