#!/usr/bin/perl -w
#
# kärlvl - extract straight taxon lists from dyntaxa/*, in turn
#          extracted and converted from <https://www.dyntaxa.se>.
# 
# Copyright (c) 2012 Jörgen Grahn
# All rights reserved.
#
# usage: kärlvl file ...
#
#

use strict;


# Perform the conversion for one file; print to stdout
#
# The columns unfortunately have different meanings in
# e.g. 'Lycopodiophyta' and 'Magnoliophyta'.  So we have to read the
# headings (the first row) before we can process the taxa.
#
# The result is:
#
# 'Familj' - turned into a section heading
#
# 'Artkomplex'
# 'Sektion'
# 'Art'
# 'Underart'
# 'Varietet'
# 'Hybrid' - turned into the Latin name
#
# 'Svenskt namn' - used if it exists
#
sub convert($) {
    my ($file) = @_;

    my %headings;

    open(F, "<$file") or die;
    while(<F>) {
	chomp;

	last if /^@/ and %headings;
	next if /^@/;
	/^(\d+)\s+=\s+(.+)/ or die;
	$headings{$2} = $1;
    }

    my $header = $headings{'Familj'} or die;
    my $sv = $headings{'Svenskt namn'} or die;
    my %la;
    foreach ('Artkomplex',
	     'Sektion',
	     'Art',
	     'Underart',
	     'Varietet',
	     'Hybrid') {
	$la{$headings{$_}}=1 if defined $headings{$_};
    }

    #print %la; print "\n"; return;

    my %CLEAR;
    my %row;

    while(<F>) {
	chomp;

	if(/^@/) {
	    if(defined $row{$header}) {
		printf "# %s\n", $row{$header};
		printf "  %s\n", $row{11};
	    }

	    %row = %CLEAR;
	    defined $row{$header} and die;
	    next;
	}

	/^(\d+)\s+=\s+(.+)/ or die;
	$row{$1} = $2;
    }

    close F;
}


foreach (@ARGV) {
    convert $_;
}

__END__
